FROM alpine:edge as builder

RUN apk update

RUN apk add -uUv erlang erlang-asn1 erlang-crypto erlang-dialyzer \
        erlang-public-key erlang-sasl erlang-ssl erlang-tools erlang-dev \
        erlang-inets erlang-syntax-tools erlang-eunit erlang-runtime-tools \
        erlang-parsetools bash elixir gcc g++

ADD . /app

WORKDIR /app

ENV MIX_ENV=prod

RUN mix do local.hex --force, local.rebar --force
RUN mix deps.clean --all
RUN mix do deps.get, deps.compile, release.clean, release

FROM alpine:edge
WORKDIR /app

RUN apk add -uUv bash p7zip

EXPOSE 80

COPY --from=builder /app/_build/prod/rel/round1/releases/0.1.0/round1.tar.gz /app

ARG bust
RUN echo $bust && tar -xzf round1.tar.gz && rm round1.tar.gz

CMD echo -n "getting ready " && date && \
    mkdir /tmp/123 && \
    cd /tmp/123 && \
    cp /tmp/data/options.txt /tmp/123 && \
    7z e /tmp/data/data.zip && \
    echo -n "running app " && date && \
    /app/bin/round1 foreground
