FROM ubuntu:zesty as builder

RUN apt-get update && apt-get -y upgrade && apt-get -y install wget locales
RUN wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && dpkg -i erlang-solutions_1.0_all.deb
RUN apt-get update && apt-get -y install esl-erlang elixir
RUN apt-get install -y gcc g++

ADD . /app

WORKDIR /app

ENV MIX_ENV=prod

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN mix do local.hex --force, local.rebar --force
RUN mix deps.clean --all
RUN mix do deps.get, deps.compile, release.clean, release

FROM ubuntu:zesty
WORKDIR /app

RUN apt-get update && apt-get -y upgrade && apt-get -y install bash libssl-dev locales p7zip-full

EXPOSE 80

COPY --from=builder /app/_build/prod/rel/round1/releases/0.1.0/round1.tar.gz /app

ARG bust
RUN echo $bust && tar -xzf round1.tar.gz

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

CMD echo -n "getting ready " && date && \
    mkdir /tmp/123 && \
    cd /tmp/123 && \
    cp /tmp/data/options.txt /tmp/123 && \
    7z e /tmp/data/data.zip && \
    echo -n "running app " && date && \
    /app/bin/round1 foreground
